samples:
    SHIP1111111: [bam_files/HiFi.sample1.bam, bam_files/HiFi.sample2.bam]
    SHIP1111112: [bam_files/HiFi.sample2.bam]
    SHIP1111113: [bam_files/HiFi.sample3.bam]
    SHIP1111114: [bam_files/HiFi.sample5.bam, bam_files/HiFi.sample6.bam]
    SHIP1111115: [bam_files/HiFi.sample6.bam]
    SHIP1111116: [bam_files/HiFi.sample7.bam]
    SHIP1111117: [bam_files/HiFi.sample8.bam]
    SHIP1111118: [bam_files/HiFi.sample9.bam]
    SHIP1111119: [bam_files/HiFi.sample10.bam, bam_files/HiFi.sample2.bam, bam_files/HiFi.sample3.bam]

metadata:
    metadata.csv