samples:
    SHIP1111111: [bam_files/hsap_hifi.1.bam, bam_files/hsap_hifi.4.bam]
    SHIP1111112: [bam_files/hsap_hifi.2.bam]
    SHIP1111113: [bam_files/hsap_hifi.3.bam]
    SHIP1111114: [bam_files/hsap_hifi.4.bam]
    SHIP1111115: [bam_files/dmel_hifi.1.bam]
    SHIP1111116: [bam_files/dmel_hifi.2.bam]
    SHIP1111117: [bam_files/dmel_hifi.3.bam]
    SHIP1111118: [bam_files/dmel_hifi.1.bam, bam_files/dmel_hifi.4.bam]
    SHIP1111119: [bam_files/dmel_illumina.1.bam]
    SHIP1111120: [bam_files/dmel_illumina.2.bam]
    SHIP1111121: [bam_files/dmel_illumina.3.bam]
    SHIP1111122: [bam_files/dmel_illumina.4.bam]

metadata:
    metadata.csv

kmer_mem_usage:
    100M